apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
  namespace: banking
data:
  01-init-postgres.sql: |
    ALTER USER postgres WITH PASSWORD 'postgres';
    GRANT ALL PRIVILEGES ON DATABASE bankingdb TO postgres;