prometheus:
  prometheusSpec:
    retention: 15d
    nodeSelector:
      kubernetes.io/hostname: worker-node-1
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 20Gi
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi

grafana:
  nodeSelector:
    kubernetes.io/hostname: worker-node-1
  persistence:
    enabled: true
    storageClassName: local-path
    size: 5Gi
  adminPassword: "StrongPassword123!"
  service:
    type: NodePort
    nodePort: 30090

alertmanager:
  alertmanagerSpec:
    nodeSelector:
      kubernetes.io/hostname: worker-node-1
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi

additionalPrometheusRulesMap:
  custom-crashloop-rule:
    groups:
      - name: custom-kubernetes-apps
        rules:
          - alert: KubePodCrashLoopingFast
            expr: max_over_time(kube_pod_container_status_waiting_reason{reason="CrashLoopBackOff"}[5m]) >= 1
            for: 30s
            labels:
              severity: warning
            annotations:
              summary: "Pod is CrashLoopBackOff"
              description: "Pod {{ $labels.namespace }}/{{ $labels.pod }} is in CrashLoopBackOff."

          - alert: KubePodOOMKilled
            expr: max_over_time(kube_pod_container_status_last_terminated_reason{reason="OOMKilled"}[5m]) >= 1
            for: 10s
            labels:
              severity: critical
            annotations:
              summary: "Pod container was OOMKilled"
              description: "Pod {{ $labels.namespace }}/{{ $labels.pod }} container {{ $labels.container }} was OOMKilled."